InfoProdAlphaVersion/MVCWEB/Models/DirectoryViewModel.cs
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;

namespace MVCWEB.Models
{
    public class DirectoryViewModel
    {
        public string Id { get; set; }
        public string value { get; set; }
        public string pseudoName { get; set; }
        public String enregistrementName { get; set; }
        public int IdHermes { get; set; }
        public List<SelectListItem> utilisateurs = new List<SelectListItem>();
        public List<SelectListItem> utilisateursPseudonames = new List<SelectListItem>();
        public List<SelectListItem> topDirectorieDirectories = new List<SelectListItem>();
        public List<SelectListItem> IdHermeses = new List<SelectListItem>();


        public List<String> files = new List<String>();
        public List<String> filesTests = new List<String>();
        public List<FileInfo> filesTestsInfo = new List<FileInfo>();
        public  List<FileSystemInfo> filesSysTestsInfo = new List<FileSystemInfo>();

        public String directoryName { get; set; }
        public int minutes { get; set; }
        public int secondes { get; set; }

        public int nbresEnrefgistrements { get; set; }
        public String enregistrementFullName { get; set; }

        public String Url { get; set; }
        public String userName { get; set; }

        public String pseudoNameEmp { get; set; }
        public String empId { get; set; }
        public String indice { get; set; }
        public string roleName { get; set; }
        public string roleKey { get; set; }
        public List<SelectListItem> compagneEnreg = new List<SelectListItem>();
        public List<SelectListItem> listeSites = new List<SelectListItem>();
        public List<SelectListItem> listeSitesV5 = new List<SelectListItem>();
        public List<SelectListItem> qualifications = new List<SelectListItem>();
        public float NombreEnregistrements { get; set; }
        public double NombreEnregistrementsTotal { get; set; }
        public String agentName { get; set; }
        public List<accueil> compagneEnregV5 = new List<accueil>();
    }

}

InfoProdAlphaVersion/MVCWEB/Controllers/DirectoryController.cs
using Domain.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MVCWEB.Models;
using NAudio.Wave;
using Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Media;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Timers;
using System.Web;
using System.Web.Mvc;

namespace MVCWEB.Controllers
{
    [Authorize(Roles = "Qualité,Manager,Agent,Agent Qualité,Agent Qualité_CustomerService,Agent Qualité_HL,Agent Qualité_Diffusion,Agent Qualité_AchatPublic,SuperManager,Agent_CustomerService, Agent_SAMRC,Agent_QR,Agent_KLMO,Agent_PRV,Agent Qualité_PRV,Agent_HL")]

    public class DirectoryController : Controller
    {
        // GET: Directory
        #region memberVariablesClass
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;
        IUtilisateurService serviceUser;
        IEmployeeService serviceEmployee;
        IGroupeEmployeeService serviceGroupeEmp;
        //static IWavePlayer playerTest;
        IWavePlayer playerTest = null;
        #endregion


        #region Constructor
        public DirectoryController()
        {
            serviceUser = new UtilisateurService();
            serviceEmployee = new EmployeeService();
            serviceGroupeEmp = new GroupesEmployeService();

        }
        public DirectoryController(ApplicationUserManager userManager, ApplicationSignInManager signInManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
            RoleManager = roleManager;
        }
        #endregion

        #region ID
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion
        #region affichage

        [Authorize(Roles = "Qualité")]
        public ActionResult Index()
        {
            //List<String> tests = new List<String>();
            //List<String> testsFiles = new List<String>();
            var a = new DirectoryViewModel();

            var tests = new DirectoryInfo(@"\\10.9.6.25\Enregistrements\DIFFUSION");
            var files = tests.EnumerateDirectories(
            "*.*",
             SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            foreach (var file in files)
            {
                // Display file path.
                a.topDirectorieDirectories.Add(new SelectListItem { Text = file.Name, Value = file.Name });

                //Console.WriteLine(file);
            }
            //  ViewBag.files = tests;
            //  var filesTests = Directory.EnumerateFiles(@"\\10.9.6.25\Enregistrements\AUTO",
            //"*.*",
            //SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            //  foreach (string file in filesTests)
            //  {
            //      // Display file path.
            //      testsFiles.Add(file);

            //      Console.WriteLine(file);
            //  }
            //  ViewBag.testsFiles = testsFiles;
            var user = UserManager.FindById(Int32.Parse(User.Identity.GetUserId()));

            //string type = form["typeGenerator"].ToString();
            var logins = serviceGroupeEmp.getListEmployeeByGroupe(user.Id);
            var us = logins.Select(o => o).Distinct().ToList();
            var uspseudoNames = logins.Select(o => o.pseudoName).Distinct().ToList();
            var ordredByPseudoNames = us.OrderBy(e => e.pseudoName).ToList();
            foreach (var test in ordredByPseudoNames)
            {
                if (!test.UserName.Equals(user.UserName))
                {
                    a.utilisateurs.Add(new SelectListItem { Text = test.UserName, Value = test.UserName });
                    a.utilisateursPseudonames.Add(new SelectListItem { Text = test.pseudoName, Value = test.pseudoName });
                    a.IdHermeses.Add(new SelectListItem { Text = "" + test.IdHermes, Value = "" + test.IdHermes });
                }

            }
            a.empId = "" + user.Id;

            a.userName = user.UserName;
            a.pseudoNameEmp = user.pseudoName;
            if (user.Content != null)
            {
                String strbase64 = Convert.ToBase64String(user.Content);
                String Url = "data:" + user.ContentType + ";base64," + strbase64;
                ViewBag.url = Url;
                a.Url = Url;

            }

            //var todayFiles = Directory.GetFiles("path_to_directory")
            //     .Where(x => new FileInfo(x).CreationTime.Date == DateTime.Today.Date);
            return View(a);
        }
        [Authorize(Roles = ("Qualité,Manager,SuperManager"))]

        public ActionResult CompagneParDate()
        {
            var a = new DirectoryViewModel();
            var files = Directory.EnumerateDirectories(@"\\10.9.6.25\Enregistrements\DIFFUSION",
                       "*.*",
                        SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            foreach (string file in files)
            {
                a.topDirectorieDirectories.Add(new SelectListItem { Text = file, Value = file });

            }
            var user = UserManager.FindById(Int32.Parse(User.Identity.GetUserId()));
            a.userName = user.UserName;
            a.pseudoNameEmp = user.pseudoName;
            if (user.Content != null)
            {
                String strbase64 = Convert.ToBase64String(user.Content);
                String Url = "data:" + user.ContentType + ";base64," + strbase64;
                ViewBag.url = Url;
                a.Url = Url;

            }
            return View(a);
        }


        [Authorize(Roles = ("Manager , Qualité,SuperManager"))]
        [HttpPost]
        public ActionResult GetChildrenofDirectory(string children)
        {
            var a = new DirectoryViewModel();
            var tests = new DirectoryInfo(@children);
            var files = tests.EnumerateDirectories("*.*",
            SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            foreach (var file in files)
            {
                // Display file path.
                a.topDirectorieDirectories.Add(new SelectListItem { Text = file.Name, Value = file.Name });

                //Console.WriteLine(file);
            }
            //if (Request.IsAjaxRequest())
            //{
            return PartialView("GetChildren", a);

            //}
            //return View("Index");
        }
        [Authorize(Roles = "Manager,SuperManager")]

        public ActionResult Index2()
        {
            //List<String> tests = new List<String>();
            //List<String> testsFiles = new List<String>();
            var a = new DirectoryViewModel();

            var tests = new DirectoryInfo(@"\\10.9.6.25\Enregistrements\DIFFUSION");
            var files = tests.EnumerateDirectories(
            "*.*",
             SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            foreach (var file in files)
            {
                // Display file path.
                a.topDirectorieDirectories.Add(new SelectListItem { Text = file.Name, Value = file.Name });

                //Console.WriteLine(file);
            }
            //  ViewBag.files = tests;
            //  var filesTests = Directory.EnumerateFiles(@"\\10.9.6.25\Enregistrements\AUTO",
            //"*.*",
            //SearchOption.TopDirectoryOnly); //search criteria for example All Directorys
            //  foreach (string file in filesTests)
            //  {
            //      // Display file path.
            //      testsFiles.Add(file);

            //      Console.WriteLine(file);
            //  }
            //  ViewBag.testsFiles = testsFiles;
            var user = UserManager.FindById(Int32.Parse(User.Identity.GetUserId()));

            //string type = form["typeGenerator"].ToString();
            var logins = serviceGroupeEmp.getListEmployeeByGroupe(user.Id);
            // (item.Roles.Any(r => r.UserId == item.Id && r.RoleId == 3))
            var us = logins.Select(o => o).Distinct().ToList();
            var uspseudoNames = logins.Select(o => o.pseudoName).Distinct().ToList();
            var ordredByPseudoNames = us.OrderBy(e => e.pseudoName).ToList();
            foreach (var test in ordredByPseudoNames)
            {
                if (!test.UserName.Equals(user.UserName) && test.Roles.Any(r => r.UserId == test.Id && r.RoleId == 3))
                {
                    a.utilisateurs.Add(new SelectListItem { Text = test.UserName, Value = test.UserName });
                    a.utilisateursPseudonames.Add(new SelectListItem { Text = test.pseudoName, Value = test.pseudoName });
                    a.IdHermeses.Add(new SelectListItem { Text = "" + test.IdHermes, Value = "" + test.IdHermes });
                }

            }
            a.empId = "" + user.Id;

            a.userName = user.UserName;

InfoProdAlphaVersion/MVCWEB/Views/Directory/CustomEnregistrement.cshtml
@model MVCWEB.Models.DirectoryViewModel
<div id="detailsFile" class="modal fade"  role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#26A69A;">
                <button type="button" id="fermer" data-id="@Model.pseudoName" class="close" data-dismiss="modal">&times;</button>
                <h5><font color="white">Details : Enregistrement</font></h5>
            </div>
            <div class="modal-body">
                <p>
                    <h10>
                         <b>Nom d'Enregistrement selectionnée :</b><br/><br/>
                         <font color="black">@Html.DisplayFor(modelItem => modelItem.pseudoName)</font>
                    </h10>
                </p>
                <br/><br/><br/>
                <div>
                    <audio controls>
                    <source src="~/Files/@Model.pseudoName" type="audio/wav" >
                    </audio>
                    <br /><br />
                    <i class="icon-download"><a style="align-self:center" href="~/Files/@Model.pseudoName" title="download" download="@Model.pseudoName">
                    Télecharger Enregistrement
                    </a></i>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="fermer2" data-id="@Model.pseudoName" class="btn bg-teal-400" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on("click", "#fermer", function () {
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            $.ajax({
                url: '/Directory/deleteEnregistrement',
                type: 'GET',
                datatype: 'json',
                async: true,
                data:{
                    'name':id
                },
                success: function (data) {
                    $("div.modal-backdrop.fade.in").remove();
                    $("#fermer").removeAttr('data-id');
                    $("#fermer2").removeAttr('data-id');
                //   $('#details').html(data);
                //   $('#Sound').modal('show');
                //    //$('#errorFile2').modal('show');
                 //alert("utilisateur success");
                },
                //complete: function () {
                //    $('#loadimage').hide();
                //    $('#details').show();

                //}
            });
        })
    })
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on("click", "#fermer2", function () {
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            $.ajax({
                url: '/Directory/deleteEnregistrement',
                type: 'GET',
                datatype: 'json',
                async: true,
                data:{
                    'name':id
                },
               success: function (data) {
                   $("div.modal-backdrop.fade.in").remove();
                   $("#fermer").removeAttr('data-id');
                   $("#fermer2").removeAttr('data-id');
                },
                
            });
        })
    })
</script>

InfoProdAlphaVersion/MVCWEB/Views/Directory/Details.cshtml
@model MVCWEB.Models.DirectoryViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_user.cshtml";
}

<h2>Details</h2>

@section test{

 
<div class="form-group">
    <div class="col-lg-10">
        @Html.TextBox("test", null, new { @class = "form-control", @id = "typeGenerator" })




    </div>
    <div class="col-md-10">
        @Html.DropDownList("typeGenerator", Model.utilisateurs, htmlAttributes: new { @class = "bootstrap-select", @id = "typeGenerator", @name = "typeGenerator", style = "data-width: 360px;", selected = "selected" })
        @Html.ValidationMessageFor(model => model.utilisateurs, "", new { @class = "text-danger" })
    </div>

</div>
<br/><br />
<br />
<br />
<br />
<br />
<br />

    <div class="row">
        @foreach (var item in @ViewBag.files)
        {
            <div class="col-lg-3 col-sm-6">

                <div class="thumbnail" style="height:300px;width:300px;">


                    <div class="thumb thumb-rounded" >
                        <a href="@Url.Action("Details", "Directory", new { enctype = "multipart/form-data" ,Value=item})" @*id="statimg" data-toggle="modal" data-id="@item.Id"*@>
                            <img href="#" src="~/Content/smart_folders_icon.png" alt="">
                        </a>
                        @*<div class="caption-overflow">
                                <span>
                                    <a href="@item.image" data-popup="lightbox" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-plus3"></i></a>
                                    <a href="#" class="btn border-white text-white btn-flat btn-icon btn-rounded ml-5"><i class="icon-link2"></i></a>
                                </span>
                            </div>*@

                    </div>

                    <div class="caption text-center">

                        <h6 class="no-margin-top text-semibold"><a href="#" class="text-default">@Html.DisplayFor(modelItem => item)</a></h6>



                    </div>

                </div>

            </div>
        }
    @foreach (var item in @ViewBag.testsFiles)
    {
        <div class="col-lg-3 col-sm-6">

            <div class="thumbnail" style="height:300px;width:300px;">


                <div class="thumb thumb-rounded">

                    <a href="" @*id="statimg" data-toggle="modal" data-id="@item.Id"*@>
                        <img href="#" src="~/Content/conffile.png" alt="">
                    </a>

                    @*<div class="caption-overflow">
                            <span>
                                <a href="@item.image" data-popup="lightbox" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-plus3"></i></a>
                                <a href="#" class="btn border-white text-white btn-flat btn-icon btn-rounded ml-5"><i class="icon-link2"></i></a>
                            </span>
                        </div>*@

                </div>

                <div class="caption text-center">
                    @*@Html.ActionLink("Details", "Details", "Directory", new { value = item }, new { enctype = "multipart/form-data" })*@


                    <h6 class="no-margin-top text-semibold"><a href="#" class="text-default">@Html.DisplayFor(modelItem => item)</a></h6>



                </div>

            </div>

        </div>
    }
</div>
}

InfoProdAlphaVersion/MVCWEB/Views/Directory/DiffusionManager.cshtml
@{
    ViewBag.Title = "Diffusion";
    Layout = "~/Views/Shared/_Layout_user.cshtml";
}
@model MVCWEB.Models.DirectoryViewModel

@section test{
    <script type="text/javascript" src="/Content/template/Layout 1/LTR/assets/js/plugins/pickers/daterangepicker.js"></script>


    <div class="form-group">
        <div class="row">
            <div class="col-1">
                <div class="col-xs-4">
                    <label>PseudoName de l'agent: </label>
                </div>
                <div class="col-xs-4">
                    <label>IdHermés de l'agent: </label>
                </div>
                <div class="col-xs-4">
                    <label>Enregistrements entre deux dates: </label>
                </div>
            </div>
        </div>
        <div class="row">


            <div class="col-1">
                <div class="col-xs-4">

                    @Html.DropDownList("PseudoName", Model.utilisateursPseudonames, htmlAttributes: new { @class = "bootstrap-select", @id = "PseudoName", @name = "PseudoName", style = "data-width: 360px;", selected = "selected" })
                    @Html.ValidationMessageFor(model => model.utilisateursPseudonames, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.DropDownList("IdHermeses", new SelectList(string.Empty, "Value", "Text"), new { style = "height: 35px;", @class = "form-control" })
                    @*@Html.DropDownList("IdHermeses", Model.IdHermeses, htmlAttributes: new { @class = "bootstrap-select", @id = "IdHermeses", @name = "IdHermeses", style = "data-width: 360px;", selected = "selected" })
                        @Html.ValidationMessageFor(model => model.IdHermeses, "", new { @class = "text-danger" })*@
                </div>
                <div class="col-xs-4">

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                            <input type="text" class="form-control daterange-basic" name="datetimes" id="datetimes" value="01/04/2019 - 10/05/2019">
                        </div>
                    </div>
                </div>
            </div>

            <br />
            <br />
            <br />

            <div class="col-1" style="margin-left:30px">
                <button id="imedSave" type="submit" class="btn bg-teal-400" data-title="Chercher Enregistrement" value="Chercher Enregistrement" data-toggle="modal">Recherche <i class="icon-arrow-right14 position-fixed"></i></button>
                @*<button id="stopRecherche" type="submit" class="btn btn-danger" data-title="Annuler la recherche" value="Chercher Enregistrement" data-toggle="modal">Annuler  <i class="icon-switch2"></i></button>*@

            </div>
            <div>
                <font color="red">@ViewBag.message</font>
            </div>
        </div>
    </div>





    <br />

    <div id="explore1">
    </div>
    <div class="row">
        <div class="col-lg-3 col-sm-6">
        </div>

        <div class="col-lg-3 col-sm-6">
            <img id="loadimage" src="~/Content/Loading-GIF-Image-3.gif" style="display: none; align-content:center" />

        </div>
        <div class="col-lg-3 col-sm-6">

        </div>

    </div>

    <script>
        $('#datePicker')
               .daterangepicker({
                   singleDatePicker: true,
                   locale: {
                       setDate: new Date(),
                       format: 'DD/MM/YYYY',
                       "daysOfWeek": [
            "Dim",
            "Lun",
            "Mar",
            "Mer",
            "Jeu",
            "Ven",
            "Sam"
                       ],
                       "monthNames": [
                           "Jan",
                           "Fev",
                           "Mar",
                           "Avr",
                           "Mai",
                           "Ju",
                           "Jui",
                           "Aou",
                           "Sep",
                           "Oct",
                           "Nov",
                           "December"
                       ],
                   },
                   lan: 'fr',
                   autoclose: true,
               })
               .on('changeDate', function (e) {
                   $('#datepicker').hide();
               });

    </script>
    <script>
    var debut;
    var fin;
$(function() {
    $('#datetimes').daterangepicker({

        opens: 'left',
        format: 'DD/MM/YYYY',
        locale: {

            "daysOfWeek": [
      "Dim",
      "Lun",
      "Mar",
      "Mer",
      "Jeu",
      "Ven",
      "Sam"
            ],
            "monthNames": [
                "Jan",
                "Fev",
                "Mar",
                "Avr",
                "Mai",
                "Ju",
                "Jui",
                "Aou",
                "Sep",
                "Oct",
                "Nov",
                "December"
            ],
        },
        lan: 'fr',


    },
     function (start, end, label) {
         debut = start.format('DD/MM/YYYY');
         fin = end.format('DD/MM/YYYY');
     }
    );
});
    </script>
    <script type="text/javascript">

        $(document).ready(function () {
            $(document).on("click", "#imedSave", function () {

                //alert(fin);
                $('#explore1').hide();

                $('#loadimage').show();

                $.ajax({
                    url: '/Directory/FindDiffusion2',
                    type: 'GET',
                    datatype: 'json',
                    data: {
                        utilisateurs: $("#IdHermeses").val(),
                        //date: $("#datePicker").val(),
                        pseudoNames: $("#PseudoName").val(),
                        start: debut,
                        end: fin
                    },
                    async: true,
                    success: function (data) {
                        $('#explore1').html(data);
                        $('#errorFile').modal('show');
                        $('#errorFile2').modal('show');
                        $('#errordate').modal('show');

                        //alert("utilisateur"+" "+$("#typeGenerator").val()+" "+""+ $("#datePicker").val())
                    },
                    complete: function () {
                        $('#loadimage').hide();
                        $('#explore1').show();

                    }
                });
            })
        })
    </script>
    <script>
    $(document).ready(function () {
        $(document).on("click", "#stopRecherche", function () {

                //alert(fin);

            $('#explore1').show();

            $('#loadimage').hide();
                $.ajax({
                    url: '/Directory/AnnulerRecherche',
                    type: 'GET',
                    datatype: 'json',
                    data: {

                    },
                    async: true,
                    //success: function (data) {
                    //    $('#explore1').html(data);
                    //    $('#errorFile').modal('show');
                    //    $('#errorFile2').modal('show');
                    //    $('#errordate').modal('show');

                    //    //alert("utilisateur"+" "+$("#typeGenerator").val()+" "+""+ $("#datePicker").val())
                    //},
                    //complete: function () {
                    //    $('#loadimage').hide();
                    //    $('#explore1').show();

                    //}
                });
            })
        })
    </script>
    <script>
        $(document).ready(function () {

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetIdHermes", "Directory")',
                dataType: 'json',
                data: {
                    PseudoNameSelected: $("#PseudoName").val()
                },
                success: function (IdHermesesList) {
                    $.each(IdHermesesList, function (i, t) {
                        $("#IdHermeses").append('<option value="' + t.Value + '">' +
                         t.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })

        $('#PseudoName').on('change', function () {
            $("#IdHermeses").empty();
           $.ajax({
                type: 'POST',
                url: '@Url.Action("GetIdHermes")',
                dataType: 'json',
                data: {
                    PseudoNameSelected: $("#PseudoName").val()
                },
                success: function (IdHermesesList) {
                    $.each(IdHermesesList, function (i, t) {
                        $("#IdHermeses").append('<option value="' + t.Value + '">' +
                         t.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    </script>
}
@section testProfile{

    <a class="dropdown-toggle" data-toggle="dropdown">
        <img src=@Model.Url alt="">
        <span>@Model.userName</span>
        <i class="caret"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-right">

        <li><a href="@Url.Action("logout", "Authentification")"><i class="icon-switch2"></i> Logout</a></li>
    </ul>
}
@section sidebarProfile{

    <a href="#" class="media-left"><img src=@Model.Url class="img-circle img-sm" alt=""></a>
    <div class="media-body">
        <span class="media-heading text-semibold">@Model.userName</span>
        <div class="text-size-mini text-muted">
            <i class="icon-user text-size-small"></i> &nbsp;@Model.pseudoNameEmp
        </div>
    </div>
    <div class="media-right media-middle">

    </div>
}
@section pagetitle{
    <h4> <span class="text-semibold">Espace Qualité</span> -  Accès aux Enregistrements</h4>
}
@section pagetitlebody{
    <li><a href="#"><i class="icon-home2 position-left"></i> Accès aux Enregistrements</a></li>
    <li class="active">Par Agent</li>
}

InfoProdAlphaVersion/MVCWEB/Views/Directory/FileError.cshtml
@model MVCWEB.Models.DirectoryViewModel
<div class="modal fade" id="errorFile2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h5>Erreur : Pas d'Enregistrements Existants</h5>
                </div>
                <div class="modal-body">
                    <p>
                        <h10>
                            Le dossier que vous avez selectionné ne contient pas un enregistrement
                            correspondant a votre recherche pour l'agent @Html.DisplayFor(modelItem => modelItem.pseudoName)
                        </h10>
                    </p>
                </div>
            </div>
        </div>

 </div>

InfoProdAlphaVersion/MVCWEB/Views/Directory/SelectDateErreur.cshtml
@model MVCWEB.Models.DirectoryViewModel
<div class="modal fade" id="errordate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5>Erreur : vous n'avez pas selectionné une date</h5>
            </div>
           <div class="modal-body">
                <p>
                    <h10>
                        Assurer vous de selectionner une date avant de rechercher a nouveau.
                    </h10>
                </p>
            </div>
        </div>
    </div>

</div>